### PR TITLE
MSVC Toolchain / Windows ARM64 Support

### PR DESCRIPTION
**Pull request by ryank231231**

### CODE REVIEW

**Comment by YuriSizuku** [comment]
Thank you for your contribution. 
It seems that some ci builds failed.  There's  a bug in `pull request, release`. I'll fix it soon.

**Comment by YuriSizuku** [comment]
I found another problem, the github ci for building by msvc takes a long time. Have you test this ci ? 
https://github.com/YuriSizuku/OnscripterYuri/actions/runs/4497516133

**Comment by ryank231231** [comment]
The MSVC toolchain currently utilizes vcpkg as its package manager. When building the target, vcpkg compiles all the required dependencies during the CI stage. This initial compilation may be slow due to the number of dependencies that need to be compiled. 

Fortunately, the CI system utilizes a cache to avoid unnecessary recompilation of certain dependencies. This means that subsequent builds will be faster as long as the cache is not expired.

**Comment by YuriSizuku** [comment]
> The MSVC toolchain currently utilizes vcpkg as its package manager. When building the target, vcpkg compiles all the required dependencies during the CI stage. This initial compilation may be slow due to the number of dependencies that need to be compiled.
> 
> Fortunately, the CI system utilizes a cache to avoid unnecessary recompilation of certain dependencies. This means that subsequent builds will be faster as long as the cache is not expired.

Thank you for telling the usage of vcpkg. At first I thought it was just like pacman in msys2, download the prebuild libraries.  If it builds from the source, it is resonable to take a long time.

**Pull request merged**
