### PR TITLE
libretro: Support build for android

### PR DESCRIPTION
**Pull request by iyzsong**
Hello, this add android build support for libretro, minimal api is 21 (Android 5).

### CODE REVIEW

**Comment by YuriSizuku** [comment]
How to use the libretro in android ?

**Comment by iyzsong** [comment]
> How to use the libretro in android ?

Via RetroArch, install the core and  core info file, then load a `nscript.dat` as game:

1. build the core with cmake (from android's ndk)
2. use `adb push` to upload `onsyuri_libretro_android.so` to `/sdcard/RetroArch/downloads`, `onsyuri_libretro.info` to `/sdcard/RetroArch/info`
3. run RetroArch on Android, in `Load Core`, select "Install or Restore a Core", then pick `onsyuri_libretro_android.so`
   In `Settings->Directory`, change `Core Info` to `/sdcard/RetroARch/info` (which usually as `/storage/emulated/0/RetroArch/info`.
4. then in `Load Core`, you should see `ONScripter Yuri` instead of `onsyuri_libretro_android.so`, if not then ensure the core info directory is correct (should include the info file) in step 3.
5. then in `Load Content` pick `nscript.dat` in a game directory.

Later we can  merge the  into file into libretro's upstream, then we won't need to do the info directory settings, just install the so core.  We can also merge the core into libretro's CI (require `.gitlab-ci.yaml` into this repo, add some doc to libretro, and contact the upstream), so that users can download the core via RetroArch.

**Comment by iyzsong** [comment]
> How to use the libretro in android ?

Via RetroArch, install the core and  core info file, then load a `nscript.dat` as game:

1. build the core with cmake, with toolchain  from android's ndk
2. use `adb push` to upload `onsyuri_libretro_android.so` to `/sdcard/RetroArch/downloads`, `onsyuri_libretro.info` to `/sdcard/RetroArch/info`
3. run RetroArch on Android, in `Load Core`, select "Install or Restore a Core", then pick `onsyuri_libretro_android.so`.
   Also in `Settings->Directory`, change `Core Info` to `/sdcard/RetroARch/info` (which usually as `/storage/emulated/0/RetroArch/info`.
4. then in `Load Core`, you should see `ONScripter Yuri` instead of `onsyuri_libretro_android.so`, if not then ensure the core info directory is correct (should include the info file) in step 3.
5. then in `Load Content` pick `nscript.dat` in a game directory.

Later we can  merge the  into file into libretro's upstream, then we won't need to do the info directory settings, just install the so core.  We can also merge the core into libretro's CI (require `.gitlab-ci.yaml` into this repo, add some doc to libretro, and contact the upstream), so that users can download the core via RetroArch.

**Comment by YuriSizuku** [comment]
Ok, I see. Thank you for your information.

**Pull request merged**
